### ISSUE TITLE
Simple Map plugin breaks when Comand Palette enabled

### ISSUE THREAD

**Issue by juresrpcic** [am-impact/amcommand#33] opened 2017-12-07 19:16 UTC
I'm not sure which plugin is causing the issue, but this issue: https://github.com/ethercreative/simplemap/issues/61 explains how having Command Palette enabled breaks Craft CP entirely by causing this error:
```
Internal Server Error
Call to a member function getMap() on null
```
This is the comment from Simple Map author:
> That error suggests that the field type was being called in some way before the rest of the plugin had been initialised. It's most likely that one of the other plugins you had installed was causing this.

The original issue has my logs and this might help figuring out the issue as well:
> If I just uninstall that one (Command Palette plugin), I can create the Map field again. But funny enough, once I create the map field, I can re-enable Command Palette and then I can continue creating Map fields without errors.

Thanks for the great plugin, I hope I can re-enable it soon.

**Comment by hubertprein** [comment] 2017-12-11 15:52
I haven't had the chance to test this yet, but for now, you're the only one experiencing this "weird bug". When I get the time (might be the end of this week) I'll install that Simple Map plugin to see what's going on. I'll get back on this.

**Comment by juresrpcic** [comment] 2017-12-11 16:00
Thanks, @hubertprein . You should be able to duplicate my error on a clean Craft 3 RC1 install doing these steps:
- install Simple Map & Command Palette plugins (and enable both)
- try to create a Simple Map field with default settings

**Comment by hubertprein** [comment] 2017-12-15 12:30
It's caused by the following check in the init function of the command palette: `Craft::$app->getUser()->getIsGuest()` That function somehow loads up a bunch of stuff, including the field type of SimpleMap. In my opinion, it shouldn't even be fired/called when checking a user status. I've brought it to Brandon's attention. We'll have to wait and see what he can say about it.

**Comment by hubertprein** [comment] 2017-12-15 14:34
@juresrpcic It seems you have to be careful with the init function. Simply register for events, but do checks **in** the triggered Event rather than in the init function. In short; fixed in the latest release.

**Closed as completed by hubertprein** 2017-12-15 14:34 UTC
